### ISSUE TITLE
publishing to multiple sessions 

### ISSUE THREAD

**Issue by sota1994** [AndreiMisiukevich/OpenTok-Xamarin.Forms#33]
Hi,
I need to publish my front camera to multiple 1:1 sessions. What should I do to achieve that? I tried to modify OpenTokPlatformService class to create multiple instances, but unfortunately when my device was publishing to the second session the stream in the first one stopped.
I hope to hear back from you soon.
Dung

**Comment by AndreiMisiukevich** [comment]
Hi, unfortunately, the current implementation doesn't allow us to achieve it.
I am not sure if it even possible, but in theory, we should create several Services instead of using CrossOpenTok

Every renderer should use its own service implementation (One service per session).

Maybe you can use group call but just don't show "redundant" participants?

**Comment by sota1994** [comment]
Thank you for your response.
Yes, I think using group call might be a more viable solution, for I don't want to modify existing code too much.
Again, thank you for your help.
